device:
  name: MyrtStrip
  id: myrt_ledstrip
wifi:
  ssid: Your SSID
  password: Your password
  start_delay: 100
mqtt:
  host: "mqtt.local"
  port: 1883
  buffer_size: 1024
ota:
  port: 3200
light:
  pin_ctl: 18
  led_count: 85
  color:
    correction: 0xFFAA78
    mireds_initial: 200
    mireds_warm: 500
    mireds_cold: 135
  brightness:
    initial: 128
    connected: 230
  transition:
    color: 700
