device:
  name: MyrtLightCeiling
  id: myrt_light_ceiling
mqtt:
  namespace: myrt/light_ceiling
light:
  pin_ctl: 25
  led_count: 23 # 23 * 15 = 345
  controller: $raw WS2811
  color:
    correction: 0xFFAA78
    mireds_initial: 350
    mireds_warm: 500
    mireds_cold: 135
    order: $raw BGR
  brightness:
    initial: 10
    connected: 100
    max: 180
  transition:
    color: 300
